### ISSUE TITLE
Issue in index.html(GUI)

### ISSUE THREAD

**Issue by ankurshaswat** [devclub-iitd/sendata#2]
The images for fb and github are too small
![image](https://cloud.githubusercontent.com/assets/24356283/26118606/2972d56a-3a88-11e7-8330-58a257250972.png)

**Comment by SkullTech** [comment]
Looks like this issue is fixed. Should I close it? @ankurshaswat 
![sendata](https://cloud.githubusercontent.com/assets/16862545/26420027/2642bfec-40df-11e7-95db-34d9814100c9.JPG)
