### ISSUE TITLE
Fix security issues shown on github

### ISSUE THREAD

**Issue by ankurshaswat** [devclub-iitd/SenData#21]

**Comment by arpit-saxena** [comment]
I can't see the security issues. I think they're only shown to the owners.

**Comment by ankurshaswat** [comment]
![Screenshot from 2019-07-26 13-56-37](https://user-images.githubusercontent.com/24356283/61937792-40084e80-afad-11e9-96e2-07fa273f03bb.png)


Also check other issues.

**Comment by arpit-saxena** [comment]
Should be fixed now.
